listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
  max_connections = 1024
}

authentication {
  enable = true
  backend = "built_in_database"
}