import { Router } from 'express'
import * as controller from './device-instance.controller'

export const deviceInstanceRouter = Router()

deviceInstanceRouter.get('/', controller.getDeviceInstances)
deviceInstanceRouter.get('/all', controller.getAllDeviceInstances)
deviceInstanceRouter.get('/groups', controller.getGroups)
deviceInstanceRouter.get('/gateway/:gatewayId', controller.getDeviceInstancesByGatewayId)
deviceInstanceRouter.put('/device-points/:pointId', controller.updateDevicePoint)
deviceInstanceRouter.delete('/device-points/:pointId', controller.deleteDevicePoint)
deviceInstanceRouter.get('/:id', controller.getDeviceInstanceById)
deviceInstanceRouter.get('/:id/device-points', controller.getDevicePoints)
deviceInstanceRouter.post('/', controller.createDeviceInstanceFull)
deviceInstanceRouter.post('/legacy', controller.createDeviceInstance)
deviceInstanceRouter.post('/batch', controller.batchCreateDeviceInstances)
deviceInstanceRouter.post('/batch-create', controller.batchCreateDevices)
deviceInstanceRouter.post('/batch-upgrade-template', controller.batchUpgradeTemplate)
deviceInstanceRouter.post('/:id/device-points', controller.createDevicePoint)
deviceInstanceRouter.put('/:id', controller.updateDeviceInstance)
deviceInstanceRouter.put('/:id/gateway', controller.changeGateway)
deviceInstanceRouter.put('/:id/sync-points', controller.syncPoints)
deviceInstanceRouter.post('/:id/enable', controller.enableDevice)
deviceInstanceRouter.post('/:id/disable', controller.disableDevice)
deviceInstanceRouter.get('/:id/template-points', controller.getTemplatePoints)
deviceInstanceRouter.get('/:id/merged-points', controller.getMergedPoints)
deviceInstanceRouter.get('/:id/deploy-config', controller.getDeviceConfigForDeploy)
deviceInstanceRouter.get('/:id/realtime-data', controller.getDeviceRealtimeData)
deviceInstanceRouter.get('/:id/history-data', controller.getDeviceHistoryData)
deviceInstanceRouter.post('/:id/upgrade-template', controller.upgradeTemplateVersion)
deviceInstanceRouter.delete('/:id', controller.deleteDeviceInstance)
